// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// updatestep_saddlenode_additive_model
Rcpp::NumericVector updatestep_saddlenode_additive_model(double X_0, Rcpp::NumericVector lambda_t, double A, double m, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_saddlenode_additive_model(SEXP X_0SEXP, SEXP lambda_tSEXP, SEXP ASEXP, SEXP mSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_t(lambda_tSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_saddlenode_additive_model(X_0, lambda_t, A, m, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}
// updatestep_saddlenode_sqrt_model
Rcpp::NumericVector updatestep_saddlenode_sqrt_model(double X_0, Rcpp::NumericVector lambda_t, double A, double m, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_saddlenode_sqrt_model(SEXP X_0SEXP, SEXP lambda_tSEXP, SEXP ASEXP, SEXP mSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_t(lambda_tSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_saddlenode_sqrt_model(X_0, lambda_t, A, m, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}
// updatestep_saddlenode_linear_model
Rcpp::NumericVector updatestep_saddlenode_linear_model(double X_0, Rcpp::NumericVector lambda_t, double A, double m, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_saddlenode_linear_model(SEXP X_0SEXP, SEXP lambda_tSEXP, SEXP ASEXP, SEXP mSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_t(lambda_tSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_saddlenode_linear_model(X_0, lambda_t, A, m, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}
// updatestep_saddlenode_t_dist
Rcpp::NumericVector updatestep_saddlenode_t_dist(double X_0, Rcpp::NumericVector lambda_t, double A, double m, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_saddlenode_t_dist(SEXP X_0SEXP, SEXP lambda_tSEXP, SEXP ASEXP, SEXP mSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_t(lambda_tSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_saddlenode_t_dist(X_0, lambda_t, A, m, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}
// updatestep_saddlenode_F_dist
Rcpp::NumericVector updatestep_saddlenode_F_dist(double X_0, Rcpp::NumericVector lambda_t, double A, double m, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_saddlenode_F_dist(SEXP X_0SEXP, SEXP lambda_tSEXP, SEXP ASEXP, SEXP mSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_t(lambda_tSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_saddlenode_F_dist(X_0, lambda_t, A, m, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}
// updatestep_saddlenode_jacobi
Rcpp::NumericVector updatestep_saddlenode_jacobi(double X_0, Rcpp::NumericVector lambda_t, double A, double m, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_saddlenode_jacobi(SEXP X_0SEXP, SEXP lambda_tSEXP, SEXP ASEXP, SEXP mSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_t(lambda_tSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_saddlenode_jacobi(X_0, lambda_t, A, m, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}
// updatestep_OU_process
Rcpp::NumericVector updatestep_OU_process(double X_0, double beta, double mu, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_OU_process(SEXP X_0SEXP, SEXP betaSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_OU_process(X_0, beta, mu, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}
// updatestep_sqrt_process
Rcpp::NumericVector updatestep_sqrt_process(double X_0, double beta, double mu, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_sqrt_process(SEXP X_0SEXP, SEXP betaSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_sqrt_process(X_0, beta, mu, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}
// updatestep_linear_process
Rcpp::NumericVector updatestep_linear_process(double X_0, double beta, double mu, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_linear_process(SEXP X_0SEXP, SEXP betaSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_linear_process(X_0, beta, mu, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}
// updatestep_t_diffusion_process
Rcpp::NumericVector updatestep_t_diffusion_process(double X_0, double beta, double mu, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_t_diffusion_process(SEXP X_0SEXP, SEXP betaSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_t_diffusion_process(X_0, beta, mu, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}
// updatestep_F_diffusion_process
Rcpp::NumericVector updatestep_F_diffusion_process(double X_0, double beta, double mu, double sigma, double step_length, Rcpp::NumericVector dW);
RcppExport SEXP _arnesdeestimatr_updatestep_F_diffusion_process(SEXP X_0SEXP, SEXP betaSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP step_lengthSEXP, SEXP dWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type X_0(X_0SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dW(dWSEXP);
    rcpp_result_gen = Rcpp::wrap(updatestep_F_diffusion_process(X_0, beta, mu, sigma, step_length, dW));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_arnesdeestimatr_updatestep_saddlenode_additive_model", (DL_FUNC) &_arnesdeestimatr_updatestep_saddlenode_additive_model, 7},
    {"_arnesdeestimatr_updatestep_saddlenode_sqrt_model", (DL_FUNC) &_arnesdeestimatr_updatestep_saddlenode_sqrt_model, 7},
    {"_arnesdeestimatr_updatestep_saddlenode_linear_model", (DL_FUNC) &_arnesdeestimatr_updatestep_saddlenode_linear_model, 7},
    {"_arnesdeestimatr_updatestep_saddlenode_t_dist", (DL_FUNC) &_arnesdeestimatr_updatestep_saddlenode_t_dist, 7},
    {"_arnesdeestimatr_updatestep_saddlenode_F_dist", (DL_FUNC) &_arnesdeestimatr_updatestep_saddlenode_F_dist, 7},
    {"_arnesdeestimatr_updatestep_saddlenode_jacobi", (DL_FUNC) &_arnesdeestimatr_updatestep_saddlenode_jacobi, 7},
    {"_arnesdeestimatr_updatestep_OU_process", (DL_FUNC) &_arnesdeestimatr_updatestep_OU_process, 6},
    {"_arnesdeestimatr_updatestep_sqrt_process", (DL_FUNC) &_arnesdeestimatr_updatestep_sqrt_process, 6},
    {"_arnesdeestimatr_updatestep_linear_process", (DL_FUNC) &_arnesdeestimatr_updatestep_linear_process, 6},
    {"_arnesdeestimatr_updatestep_t_diffusion_process", (DL_FUNC) &_arnesdeestimatr_updatestep_t_diffusion_process, 6},
    {"_arnesdeestimatr_updatestep_F_diffusion_process", (DL_FUNC) &_arnesdeestimatr_updatestep_F_diffusion_process, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_arnesdeestimatr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
