# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updatestep_saddlenode_additive_model <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_saddlenode_additive_model`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_saddlenode_sqrt_model <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_saddlenode_sqrt_model`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_saddlenode_linear_model <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_saddlenode_linear_model`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_saddlenode_t_dist <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_saddlenode_t_dist`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_saddlenode_F_dist <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_saddlenode_F_dist`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_saddlenode_jacobi <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_saddlenode_jacobi`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_OU_process <- function(X_0, beta, mu, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_OU_process`, X_0, beta, mu, sigma, step_length, dW)
}

updatestep_sqrt_process <- function(X_0, beta, mu, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_sqrt_process`, X_0, beta, mu, sigma, step_length, dW)
}

