# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updatestep_additive_model <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_additive_model`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_sqrt_model <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_sqrt_model`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_linear_model <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_linear_model`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_t_dist <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_t_dist`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_F_dist <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_F_dist`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

updatestep_jacobi <- function(X_0, lambda_t, A, m, sigma, step_length, dW) {
    .Call(`_arnesdeestimatr_updatestep_jacobi`, X_0, lambda_t, A, m, sigma, step_length, dW)
}

